export const PLANTS = [
  {
    number: "29-670-0172",
    state: "Closed",
    short_description: "Woollyfruit Desertparsley",
    sys_created_on: "12/1/2019",
    priority: "Yellow",
    category: "Lomatium dasycarpum (Torr. & A. Gray) J.M. Coult. & Rose",
  },
  {
    number: "56-696-3732",
    state: "In Progress",
    short_description: "Hybrid Violet",
    sys_created_on: "12/9/2019",
    priority: "Puce",
    category: "Viola ×malteana House",
  },
  {
    number: "70-774-2307",
    state: "Open",
    short_description: "Silverskin Lichen",
    sys_created_on: "3/12/2020",
    priority: "Violet",
    category: "Dermatocarpon luridum (With.) J.R. Laundon",
  },
  {
    number: "72-264-1091",
    state: "Closed",
    short_description: "Beaumont Oak",
    sys_created_on: "11/27/2019",
    priority: "Teal",
    category: "Quercus ×beaumontiana Sarg.",
  },
  {
    number: "10-533-1678",
    state: "In Progress",
    short_description: "Cochlearia",
    sys_created_on: "4/7/2019",
    priority: "Mauv",
    category: "Cochlearia tridactylites Banks ex DC.",
  },
  {
    number: "50-705-5417",
    state: "In Progress",
    short_description: "Showy Alpine Ragwort",
    sys_created_on: "11/21/2019",
    priority: "Blue",
    category: "Senecio amplectens A. Gray var. amplectens",
  },
  {
    number: "49-620-9783",
    state: "In Progress",
    short_description: "California Stickseed",
    sys_created_on: "9/13/2019",
    priority: "Blue",
    category: "Hackelia californica (A. Gray) I.M. Johnst.",
  },
  {
    number: "82-066-6242",
    state: "Closed",
    short_description: "Pohlia Moss",
    sys_created_on: "10/20/2019",
    priority: "Crimson",
    category: "Pohlia sphagnicola (Bruch & Schimp.) Broth.",
  },
  {
    number: "45-144-0294",
    state: "Closed",
    short_description: "Purple Crab Apple",
    sys_created_on: "1/18/2020",
    priority: "Maroon",
    category: "Malus ×purpurea (A. Barbier) Rehder",
  },
  {
    number: "71-422-7615",
    state: "Closed",
    short_description: "Fastigiate Mouse-ear Chickweed",
    sys_created_on: "8/8/2019",
    priority: "Blue",
    category: "Cerastium fastigiatum Greene",
  },
  {
    number: "80-429-7487",
    state: "Resolved",
    short_description: "Cutleaf Nightshade",
    sys_created_on: "2/9/2020",
    priority: "Pink",
    category: "Solanum triflorum Nutt.",
  },
  {
    number: "70-533-7989",
    state: "In Progress",
    short_description: "Campylopus Moss",
    sys_created_on: "9/26/2019",
    priority: "Indigo",
    category: "Campylopus introflexus (Hedw.) Brid.",
  },
  {
    number: "39-072-0257",
    state: "In Progress",
    short_description: "Neyraudia",
    sys_created_on: "11/9/2019",
    priority: "Blue",
    category: "Neyraudia Hook. f.",
  },
  {
    number: "19-661-3424",
    state: "Resolved",
    short_description: "Hypecoum",
    sys_created_on: "6/10/2019",
    priority: "Maroon",
    category: "Hypecoum L.",
  },
  {
    number: "12-765-7826",
    state: "In Progress",
    short_description: "Thurow's Panicgrass",
    sys_created_on: "1/20/2020",
    priority: "Pink",
    category:
      "Dichanthelium acuminatum (Sw.) Gould & C.A. Clark var. thurowii (Scribn. & J.G. Sm.) Gould & C.A. Clark",
  },
  {
    number: "73-946-1470",
    state: "Resolved",
    short_description: "Hyphaene",
    sys_created_on: "9/14/2019",
    priority: "Fuscia",
    category: "Hyphaene Gaertn.",
  },
  {
    number: "62-224-1569",
    state: "Open",
    short_description: "Double Coconut",
    sys_created_on: "2/3/2020",
    priority: "Mauv",
    category: "Lodoicea maldivica (J.F. Gmel.) Pers.",
  },
  {
    number: "11-242-8977",
    state: "Open",
    short_description: "James' Cryptantha",
    sys_created_on: "9/21/2019",
    priority: "Khaki",
    category: "Cryptantha cinerea (Greene) Cronquist",
  },
  {
    number: "40-885-1664",
    state: "Closed",
    short_description: "Alsike Clover",
    sys_created_on: "7/30/2019",
    priority: "Violet",
    category: "Trifolium hybridum L.",
  },
  {
    number: "12-851-4205",
    state: "Closed",
    short_description: "Carrotwood",
    sys_created_on: "3/12/2020",
    priority: "Blue",
    category: "Cupaniopsis anacardioides (A. Rich.) Radlk.",
  },
  {
    number: "68-565-5286",
    state: "In Progress",
    short_description: "Plantain False Leopardbane",
    sys_created_on: "2/20/2020",
    priority: "Yellow",
    category: "Doronicum plantagineum L.",
  },
  {
    number: "04-243-1469",
    state: "Resolved",
    short_description: "Cushenbury Milkvetch",
    sys_created_on: "8/9/2019",
    priority: "Orange",
    category: "Astragalus albens Greene",
  },
  {
    number: "83-791-8928",
    state: "Resolved",
    short_description: "American Elm",
    sys_created_on: "7/17/2019",
    priority: "Indigo",
    category: "Ulmus americana L.",
  },
  {
    number: "13-843-4924",
    state: "Resolved",
    short_description: "Schistophragma",
    sys_created_on: "4/25/2019",
    priority: "Orange",
    category: "Schistophragma Benth. ex Endl.",
  },
  {
    number: "74-418-3841",
    state: "Closed",
    short_description: "Plains Evening Primrose",
    sys_created_on: "5/31/2019",
    priority: "Indigo",
    category: "Camissonia contorta (Douglas ex Lehm.) Kearney",
  },
  {
    number: "95-379-3460",
    state: "Closed",
    short_description: "Football Fruit",
    sys_created_on: "3/8/2020",
    priority: "Red",
    category: "Pangium edule Reinw. ex Blume",
  },
  {
    number: "69-277-6575",
    state: "Closed",
    short_description: "Sonoran Sandmat",
    sys_created_on: "7/15/2019",
    priority: "Khaki",
    category: "Chamaesyce micromera (Boiss. ex Engelm.) Wooton & Standl.",
  },
  {
    number: "77-819-6587",
    state: "In Progress",
    short_description: "Globe Cactus",
    sys_created_on: "10/14/2019",
    priority: "Blue",
    category: "Mammillaria Haw.",
  },
  {
    number: "62-643-7630",
    state: "In Progress",
    short_description: "Arizona Barley",
    sys_created_on: "11/23/2019",
    priority: "Maroon",
    category: "Hordeum arizonicum Covas",
  },
  {
    number: "36-833-5987",
    state: "In Progress",
    short_description: "Disc Lichen",
    sys_created_on: "3/19/2020",
    priority: "Pink",
    category: "Buellia curatellae Malme",
  },
  {
    number: "49-493-4668",
    state: "In Progress",
    short_description: "Creeping Lovegrass",
    sys_created_on: "12/9/2019",
    priority: "Green",
    category: "Neeragrostis reptans (Michx.) Nicora",
  },
  {
    number: "88-764-4797",
    state: "Open",
    short_description: "Glossy Buckthorn",
    sys_created_on: "11/24/2019",
    priority: "Green",
    category: "Frangula alnus Mill.",
  },
  {
    number: "70-802-7175",
    state: "Resolved",
    short_description: "Thompson's Sandwort",
    sys_created_on: "4/7/2019",
    priority: "Khaki",
    category: "Arenaria franklinii Douglas ex Hook. var. thompsonii M. Peck",
  },
  {
    number: "30-891-4981",
    state: "Open",
    short_description: "Slash Pine",
    sys_created_on: "8/21/2019",
    priority: "Indigo",
    category: "Pinus elliottii Engelm. var. elliottii",
  },
  {
    number: "68-587-2692",
    state: "Open",
    short_description: "Turbina",
    sys_created_on: "1/24/2020",
    priority: "Puce",
    category: "Turbina Raf.",
  },
  {
    number: "07-470-9515",
    state: "Open",
    short_description: "Soft Fissurewort",
    sys_created_on: "7/5/2019",
    priority: "Red",
    category: "Halimolobos mollis (Hook.) Rollins",
  },
  {
    number: "50-105-6739",
    state: "Closed",
    short_description: "Texas Sleepydaisy",
    sys_created_on: "3/6/2020",
    priority: "Puce",
    category: "Xanthisma texanum DC.",
  },
  {
    number: "13-928-3999",
    state: "Open",
    short_description: "Flyweed",
    sys_created_on: "6/11/2019",
    priority: "Yellow",
    category: "Bejaria Mutis, orth. cons.",
  },
  {
    number: "37-285-2485",
    state: "In Progress",
    short_description: "Easter Lily",
    sys_created_on: "9/4/2019",
    priority: "Goldenrod",
    category: "Lilium longiflorum Thunb.",
  },
  {
    number: "95-451-0957",
    state: "Closed",
    short_description: "Baby's Breath",
    sys_created_on: "7/19/2019",
    priority: "Crimson",
    category: "Gypsophila paniculata L.",
  },
  {
    number: "93-268-5646",
    state: "Resolved",
    short_description: "Dwarf Checkerbloom",
    sys_created_on: "12/3/2019",
    priority: "Yellow",
    category:
      "Sidalcea malviflora (DC.) A. Gray ex Benth. ssp. laciniata C.L. Hitchc. var. sancta C.L. Hitchc.",
  },
  {
    number: "34-199-6798",
    state: "Resolved",
    short_description: "Brazilian Red-cloak",
    sys_created_on: "6/22/2019",
    priority: "Yellow",
    category: "Megaskepasma Lindau",
  },
  {
    number: "48-529-1879",
    state: "In Progress",
    short_description: "Belembe Silvestre",
    sys_created_on: "5/7/2019",
    priority: "Mauv",
    category: "Xanthosoma helleborifolium (Jacq.) Schott",
  },
  {
    number: "55-045-2994",
    state: "In Progress",
    short_description: "Candyroot",
    sys_created_on: "10/28/2019",
    priority: "Teal",
    category: "Polygala nana (Michx.) DC.",
  },
  {
    number: "96-367-7234",
    state: "Closed",
    short_description: "Blue Wild Indigo",
    sys_created_on: "9/6/2019",
    priority: "Crimson",
    category:
      "Baptisia australis (L.) R. Br. var. aberrans (Larisey) M. Mendenhall",
  },
  {
    number: "87-372-0088",
    state: "In Progress",
    short_description: "Bastard Stopper",
    sys_created_on: "6/24/2019",
    priority: "Fuscia",
    category: "Petitia domingensis Jacq.",
  },
  {
    number: "80-973-8743",
    state: "Resolved",
    short_description: "Blue Lettuce",
    sys_created_on: "6/13/2019",
    priority: "Violet",
    category: "Lactuca tatarica (L.) C.A. Mey. var. pulchella (Pursh) Breitung",
  },
  {
    number: "73-419-9929",
    state: "Open",
    short_description: "Siskiyou Sedge",
    sys_created_on: "2/10/2020",
    priority: "Puce",
    category: "Carex scabriuscula Mack.",
  },
  {
    number: "53-758-8169",
    state: "Closed",
    short_description: "Creeping Tonguefern",
    sys_created_on: "8/20/2019",
    priority: "Pink",
    category: "Elaphoglossum aemulum (Kaulf.) Brack.",
  },
  {
    number: "50-214-7280",
    state: "Resolved",
    short_description: "Kamchatka Thistle",
    sys_created_on: "10/4/2019",
    priority: "Yellow",
    category: "Cirsium kamtschaticum Ledeb. ex DC.",
  },
  {
    number: "58-288-1838",
    state: "In Progress",
    short_description: "Tufted Evening Primrose",
    sys_created_on: "8/5/2019",
    priority: "Aquamarine",
    category: "Oenothera caespitosa Nutt. ssp. crinita (Rydb.) Munz",
  },
  {
    number: "73-095-7709",
    state: "Closed",
    short_description: "Littleleaf Wrightwort",
    sys_created_on: "11/2/2019",
    priority: "Violet",
    category: "Carlowrightia parvifolia Brandegee",
  },
  {
    number: "36-498-0332",
    state: "Closed",
    short_description: "Shrubland Dubautia",
    sys_created_on: "12/10/2019",
    priority: "Purple",
    category: "Dubautia linearis (Gaudich.) D.D. Keck ssp. linearis",
  },
  {
    number: "15-142-7823",
    state: "Open",
    short_description: "Kleberg's Bluestem",
    sys_created_on: "7/9/2019",
    priority: "Puce",
    category: "Dichanthium annulatum (Forssk.) Stapf",
  },
  {
    number: "64-307-8979",
    state: "Resolved",
    short_description: "Quickstick",
    sys_created_on: "2/1/2020",
    priority: "Yellow",
    category: "Gliricidia Kunth",
  },
  {
    number: "34-985-9992",
    state: "In Progress",
    short_description: "Hairy Cornsalad",
    sys_created_on: "3/1/2020",
    priority: "Purple",
    category: "Valerianella amarella (Lindh. ex Engelm.) Krok",
  },
  {
    number: "43-100-4739",
    state: "Open",
    short_description: "Florida Bully",
    sys_created_on: "11/10/2019",
    priority: "Maroon",
    category:
      "Sideroxylon reclinatum Michx. ssp. austrofloridense (Whetstone) Kartesz & Gandhi",
  },
  {
    number: "92-841-3995",
    state: "Open",
    short_description: "Hemionitis",
    sys_created_on: "5/15/2019",
    priority: "Orange",
    category: "Hemionitis L.",
  },
  {
    number: "74-681-5109",
    state: "In Progress",
    short_description: "Rocklady",
    sys_created_on: "4/22/2019",
    priority: "Green",
    category: "Holmgrenanthe Elisens",
  },
  {
    number: "06-191-2180",
    state: "Closed",
    short_description: "Curlytop Gumweed",
    sys_created_on: "5/15/2019",
    priority: "Maroon",
    category: "Grindelia nuda Alph. Wood var. aphanactis (Rydb.) G.L. Nesom",
  },
  {
    number: "84-289-5480",
    state: "Open",
    short_description: "Wilcox's Phlox",
    sys_created_on: "6/18/2019",
    priority: "Turquoise",
    category: "Phlox drummondii Hook. ssp. wilcoxiana (Bogusch) Wherry",
  },
  {
    number: "62-644-9332",
    state: "In Progress",
    short_description: "Lecania Lichen",
    sys_created_on: "8/17/2019",
    priority: "Fuscia",
    category: "Lecania toninioides Zahlbr.",
  },
  {
    number: "99-627-3877",
    state: "Open",
    short_description: "Glaucous Wild Cabbage",
    sys_created_on: "4/16/2019",
    priority: "Maroon",
    category: "Caulanthus glaucus S. Watson",
  },
  {
    number: "20-961-9893",
    state: "Resolved",
    short_description: "Cusick's Giant Hyssop",
    sys_created_on: "9/18/2019",
    priority: "Green",
    category: "Agastache cusickii (Greenm.) A. Heller",
  },
  {
    number: "59-997-4193",
    state: "Resolved",
    short_description: "Spreading Sedge",
    sys_created_on: "10/23/2019",
    priority: "Turquoise",
    category: "Carex laxiculmis Schwein. var. laxiculmis",
  },
  {
    number: "63-114-8011",
    state: "Open",
    short_description: "Fragrant Sumac",
    sys_created_on: "5/25/2019",
    priority: "Fuscia",
    category: "Rhus aromatica Aiton var. serotina (Greene) Rehder",
  },
  {
    number: "66-207-8590",
    state: "In Progress",
    short_description: "Chinese-plumbago",
    sys_created_on: "2/28/2020",
    priority: "Indigo",
    category: "Ceratostigma willmottianum Stapf",
  },
  {
    number: "41-206-9287",
    state: "Closed",
    short_description: "Scilla",
    sys_created_on: "3/20/2020",
    priority: "Pink",
    category: "Scilla L.",
  },
  {
    number: "43-720-3135",
    state: "Resolved",
    short_description: "Sagebrush Buttercup",
    sys_created_on: "12/4/2019",
    priority: "Turquoise",
    category: "Ranunculus glaberrimus Hook. var. glaberrimus",
  },
  {
    number: "77-600-5269",
    state: "In Progress",
    short_description: "Menzies' Campion",
    sys_created_on: "9/4/2019",
    priority: "Mauv",
    category: "Silene menziesii Hook. ssp. menziesii",
  },
  {
    number: "19-080-9120",
    state: "Closed",
    short_description: "Propeller Flower",
    sys_created_on: "9/27/2019",
    priority: "Indigo",
    category: "Alophia drummondii (Graham) R.C. Foster",
  },
  {
    number: "72-199-1194",
    state: "Closed",
    short_description: "Exocarpos",
    sys_created_on: "5/5/2019",
    priority: "Fuscia",
    category: "Exocarpos Labill.",
  },
  {
    number: "60-391-8513",
    state: "In Progress",
    short_description: "Nevada City Buckwheat",
    sys_created_on: "3/30/2020",
    priority: "Puce",
    category: "Eriogonum prattenianum Durand",
  },
  {
    number: "63-396-4188",
    state: "Closed",
    short_description: "Nixon's Hawthorn",
    sys_created_on: "3/7/2020",
    priority: "Teal",
    category: "Crataegus nananixonii Phipps & R. O'Kennon",
  },
  {
    number: "40-838-9276",
    state: "Open",
    short_description: "Hairy Yerba Santa",
    sys_created_on: "9/5/2019",
    priority: "Puce",
    category: "Eriodictyon trichocalyx A. Heller var. trichocalyx",
  },
  {
    number: "08-510-0579",
    state: "Closed",
    short_description: "Congdon's Buckwheat",
    sys_created_on: "9/27/2019",
    priority: "Blue",
    category: "Eriogonum congdonii (S. Stokes) Reveal",
  },
  {
    number: "68-290-8720",
    state: "Closed",
    short_description: "Mnium Calcareous Moss",
    sys_created_on: "10/16/2019",
    priority: "Aquamarine",
    category: "Mnium Hedw.",
  },
  {
    number: "22-691-8794",
    state: "Resolved",
    short_description: "Thoroughwort",
    sys_created_on: "11/27/2019",
    priority: "Pink",
    category: "Koanophyllon Arruda",
  },
  {
    number: "47-322-3795",
    state: "In Progress",
    short_description: "Grimmia Dry Rock Moss",
    sys_created_on: "8/20/2019",
    priority: "Pink",
    category: "Grimmia atrata Miel. ex Hornsch.",
  },
  {
    number: "00-149-7761",
    state: "Closed",
    short_description: "Fissurewort",
    sys_created_on: "3/22/2020",
    priority: "Purple",
    category: "Halimolobos Tausch",
  },
  {
    number: "43-076-1774",
    state: "Closed",
    short_description: "Thicket Maiden Fern",
    sys_created_on: "6/26/2019",
    priority: "Puce",
    category: "Thelypteris leptocladia (Fée) Proctor",
  },
  {
    number: "86-507-5690",
    state: "Open",
    short_description: "Pineland Golden Trumpet",
    sys_created_on: "1/21/2020",
    priority: "Khaki",
    category: "Angadenia berteroi (A. DC.) Miers",
  },
  {
    number: "61-805-3259",
    state: "In Progress",
    short_description: "Mojave Milkvetch",
    sys_created_on: "12/9/2019",
    priority: "Teal",
    category: "Astragalus mohavensis S. Watson",
  },
  {
    number: "95-242-8292",
    state: "Closed",
    short_description: "Molokai False Lobelia",
    sys_created_on: "3/11/2020",
    priority: "Orange",
    category: "Trematolobelia rockii H. St. John",
  },
  {
    number: "26-406-9736",
    state: "In Progress",
    short_description: "Catnip Noseburn",
    sys_created_on: "6/15/2019",
    priority: "Indigo",
    category: "Tragia nepetifolia Cav.",
  },
  {
    number: "58-483-8295",
    state: "Closed",
    short_description: "Canby's Lousewort",
    sys_created_on: "1/30/2020",
    priority: "Purple",
    category: "Pedicularis bracteosa Benth. var. canbyi (A. Gray) Cronquist",
  },
  {
    number: "07-011-2464",
    state: "Closed",
    short_description: "Chinese Violet",
    sys_created_on: "8/4/2019",
    priority: "Blue",
    category: "Asystasia gangetica (L.) T. Anderson",
  },
  {
    number: "86-992-1196",
    state: "In Progress",
    short_description: "Maui Tetramolopium",
    sys_created_on: "6/20/2019",
    priority: "Violet",
    category: "Tetramolopium arenarium (A. Gray) Hillebr. ssp. arenarium",
  },
  {
    number: "53-503-6254",
    state: "In Progress",
    short_description: "Spring-gold",
    sys_created_on: "4/14/2019",
    priority: "Yellow",
    category: "Crocidium Hook.",
  },
  {
    number: "38-055-6210",
    state: "Open",
    short_description: "Taylor County Blackberry",
    sys_created_on: "6/8/2019",
    priority: "Crimson",
    category: "Rubus tygartensis H.A. Davis & T. Davis",
  },
  {
    number: "10-900-0875",
    state: "In Progress",
    short_description: "Harrimanella",
    sys_created_on: "9/30/2019",
    priority: "Indigo",
    category: "Harrimanella Coville",
  },
  {
    number: "27-388-6833",
    state: "Open",
    short_description: "Ouachita Mountain Goldenrod",
    sys_created_on: "8/30/2019",
    priority: "Yellow",
    category: "Solidago ouachitensis C.E.S. Taylor & R.J. Taylor",
  },
  {
    number: "06-678-2522",
    state: "In Progress",
    short_description: "Glacial Willow",
    sys_created_on: "11/14/2019",
    priority: "Fuscia",
    category: "Salix ovalifolia Trautv. var. glacialis (Andersson) Argus",
  },
  {
    number: "52-067-9203",
    state: "Resolved",
    short_description: "Gladecress",
    sys_created_on: "6/19/2019",
    priority: "Turquoise",
    category: "Leavenworthia Torr.",
  },
  {
    number: "66-380-1630",
    state: "In Progress",
    short_description: "Small-flowered Calycadenia",
    sys_created_on: "11/17/2019",
    priority: "Yellow",
    category: "Calycadenia micrantha R.L. Carr & G.D. Carr",
  },
  {
    number: "24-566-5215",
    state: "In Progress",
    short_description: "Ribbed Cryptantha",
    sys_created_on: "8/2/2019",
    priority: "Khaki",
    category: "Cryptantha costata Brandegee",
  },
  {
    number: "81-853-9405",
    state: "In Progress",
    short_description: "Roadside Brome",
    sys_created_on: "4/23/2019",
    priority: "Crimson",
    category: "Bromus stamineus Desv.",
  },
  {
    number: "99-602-5342",
    state: "Open",
    short_description: "Eureka Milkvetch",
    sys_created_on: "11/2/2019",
    priority: "Green",
    category: "Astragalus eurekensis M.E. Jones",
  },
  {
    number: "84-722-1921",
    state: "Closed",
    short_description: "Tarweed",
    sys_created_on: "4/30/2019",
    priority: "Turquoise",
    category: "Hemizonella (A. Gray) A. Gray",
  },
  {
    number: "35-894-4351",
    state: "Open",
    short_description: "Silverleaf Milkvetch",
    sys_created_on: "5/9/2019",
    priority: "Aquamarine",
    category: "Astragalus argophyllus Nutt. var. martinii M.E. Jones",
  },
];
